#!/bin/bash
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "GRANDES VOLUMENES DE DATOS - TP2"
printf "\n"
printf '\e[1;31m%-6s\e[m' "Alumno: Ing. Gonzalo Nahuel Vaca"
printf "\n"
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "Punto 2: levantar todas las instancias"
printf "\n"
printf '\e[1;34m%-6s\e[m' "Comienzo la creación de los contenedores"
printf "\n"
docker-compose up -d
printf '\e[1;34m%-6s\e[m' "Espero 10 segundos"
printf "\n"
sleep 10
################################################################################
printf '\e[1;34m%-6s\e[m' "Inicio el replica set del shard alfa"
printf "\n"
docker-compose exec alfa01 sh -c "mongo < /scripts/alfa.js"
docker-compose exec alfa02 sh -c "mongo < /scripts/slaveOk.js"
docker-compose exec alfa03 sh -c "mongo < /scripts/slaveOk.js"
################################################################################
printf '\e[1;34m%-6s\e[m' "Inicio el replica set del shard beta"
printf "\n"
docker-compose exec beta01 sh -c "mongo < /scripts/beta.js"
docker-compose exec beta02 sh -c "mongo < /scripts/slaveOk.js"
docker-compose exec beta03 sh -c "mongo < /scripts/slaveOk.js"
################################################################################
printf '\e[1;34m%-6s\e[m' "Inicio el replica set del shard charlie"
printf "\n"
docker-compose exec charlie01 sh -c "mongo < /scripts/charlie.js"
docker-compose exec charlie02 sh -c "mongo < /scripts/slaveOk.js"
docker-compose exec charlie03 sh -c "mongo < /scripts/slaveOk.js"
################################################################################
printf '\e[1;34m%-6s\e[m' "Inicio el replica set de los servidores de configuración"
printf "\n"
docker-compose exec config01 sh -c "mongo --port 27019 < /scripts/config.js"
docker-compose exec config02 sh -c "mongo --port 27019 < /scripts/slaveOkconfig.js"
docker-compose exec config03 sh -c "mongo --port 27019 < /scripts/slaveOkconfig.js"
################################################################################
printf '\e[1;34m%-6s\e[m' "Espero 40 segundos para que se realicen las conexiones internas"
printf "\n"
sleep 40
printf '\e[1;34m%-6s\e[m' "Cargo los datos en el rs alfa"
printf "\n"
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "Se tiene resuelto los puntos 1 y 2 del trabajo práctico"
printf "\n"
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "Punto 3:"
printf "\n"
docker-compose exec alfa01 sh -c "mongo < /scripts/punto3.js"
printf "\n"
printf '\e[1;31m%-6s\e[m' "Se seleciona una clave compuesta {\"cliente.region\":1, \"cliente.nombre\": 1}"
printf "\n"
docker-compose exec alfa01 sh -c "mongo < /scripts/addIndex.js"
printf '\e[1;34m%-6s\e[m' "Configuro el router"
printf "\n"
docker-compose exec router sh -c "mongo < /scripts/init-router.js"
################################################################################
printf '\e[1;34m%-6s\e[m' "Genero los datos para el shard alfa"
printf "\n"
docker-compose exec alfa01 sh -c "mongo < /scripts/finanzas.js"
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "Punto 4, 5 y 6:"
printf "\n"
printf '\e[1;34m%-6s\e[m' "Agrego 2 nuevos shards al cluster"
printf "\n"
docker-compose exec router sh -c "mongo < /scripts/moreShards.js"
################################################################################
printf "\n"
printf '\e[1;31m%-6s\e[m' "Punto 7 y 8:"
printf "\n"
printf "\n"
printf '\e[1;34m%-6s\e[m' "En este momento se están balanceando el cluster, se recomienda esperar unos minutos"
printf "\n"
printf "\n"
printf '\e[1;34m%-6s\e[m' "Cuando lo crea conveniente, ejecute './consultas.sh' (recuerde darle permisos con chmod +x finalizar.sh)"
printf "\n"
printf "\n"
printf '\e[1;34m%-6s\e[m' "Cuando quiera finalizar este laboratorio y destruir todo lo creado, ejecute './finalizar.sh' (recuerde darle permisos con chmod +x finalizar.sh)"
printf "\n"